/** 11.12.2019 Actualizar FLech asociando socio con persona, existentes **/
update socio set idpersona = 	2	 where idsocio = 	806	;
update socio set idpersona = 	8	 where idsocio = 	803	;
update socio set idpersona = 	10	 where idsocio = 	805	;
update socio set idpersona = 	15	 where idsocio = 	809	;
update socio set idpersona = 	21	 where idsocio = 	241	;
update socio set idpersona = 	65	 where idsocio = 	808	;
update socio set idpersona = 	74	 where idsocio = 	620	;
update socio set idpersona = 	75	 where idsocio = 	290	;
update socio set idpersona = 	80	 where idsocio = 	621	;
update socio set idpersona = 	86	 where idsocio = 	811	;
update socio set idpersona = 	88	 where idsocio = 	812	;
update socio set idpersona = 	94	 where idsocio = 	659	;
update socio set idpersona = 	102	 where idsocio = 	655	;
update socio set idpersona = 	105	 where idsocio = 	773	;
update socio set idpersona = 	107	 where idsocio = 	661	;
update socio set idpersona = 	108	 where idsocio = 	772	;
update socio set idpersona = 	109	 where idsocio = 	245	;
update socio set idpersona = 	142	 where idsocio = 	810	;
update socio set idpersona = 	188	 where idsocio = 	802	;
update socio set idpersona = 	268	 where idsocio = 	651	;
update socio set idpersona = 	270	 where idsocio = 	650	;
update socio set idpersona = 	271	 where idsocio = 	649	;
update socio set idpersona = 	272	 where idsocio = 	648	;
update socio set idpersona = 	287	 where idsocio = 	647	;
update socio set idpersona = 	293	 where idsocio = 	646	;
update socio set idpersona = 	299	 where idsocio = 	248	;
update socio set idpersona = 	330	 where idsocio = 	770	;
update socio set idpersona = 	332	 where idsocio = 	652	;
update socio set idpersona = 	333	 where idsocio = 	769	;
update socio set idpersona = 	360	 where idsocio = 	675	;
update socio set idpersona = 	381	 where idsocio = 	762	;
update socio set idpersona = 	524	 where idsocio = 	657	;
update socio set idpersona = 	526	 where idsocio = 	658	;
update socio set idpersona = 	548	 where idsocio = 	619	;
update socio set idpersona = 	570	 where idsocio = 	249	;
update socio set idpersona = 	576	 where idsocio = 	238	;
update socio set idpersona = 	578	 where idsocio = 	270	;
update socio set idpersona = 	579	 where idsocio = 	628	;
update socio set idpersona = 	580	 where idsocio = 	281	;
update socio set idpersona = 	699	 where idsocio = 	792	;
/** Fin Actualizar FLech **/

/** Insertando entidad **/
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	710	,	3783426	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	711	,	44734	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	712	,	237	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	713	,	238	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	714	,	3150879	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	715	,	779787	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	716	,	2893026	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	717	,	706658	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	718	,	742481	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	719	,	246	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	720	,	247	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	721	,	248	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	722	,	2875670	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	723	,	6496144	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	724	,	5210699	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	725	,	957156	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	726	,	4479621	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	727	,	6407362	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	728	,	9370502	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	729	,	852874	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	730	,	8827133	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	731	,	2915284	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	732	,	8825277	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	733	,	6502841	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	734	,	3516075	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	735	,	3155652	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	736	,	6517707	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	737	,	3584413	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	738	,	3584413	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	739	,	4440545	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	740	,	3587514	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	741	,	9387304	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	742	,	7898751	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	743	,	8008717	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	744	,	34510755	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	745	,	829665	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	746	,	948461	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	747	,	4446321	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	748	,	4424445	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	749	,	3037955	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	750	,	980210	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	751	,	3762274	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	752	,	801565	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	753	,	3797766	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	754	,	905328	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	755	,	6514002	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	756	,	4476301	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	757	,	4389493	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	758	,	12715583	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	759	,	5214566	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	760	,	8714246	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	761	,	4416969	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	762	,	5240852	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	763	,	4438067	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	764	,	4524989	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	765	,	5219517	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	766	,	9480373	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	767	,	5153206	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	768	,	6479554	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	769	,	9480098	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	770	,	3154156	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	771	,	6423993	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	772	,	4429672	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	773	,	6461116	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	774	,	832898	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	775	,	4498531	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	776	,	3777835	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	777	,	8699451	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	778	,	5294501	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	779	,	5310423	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	780	,	12344644	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	781	,	5319644	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	782	,	000	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	783	,	956569	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	784	,	772759	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	785	,	5210907	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	786	,	3028816	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	787	,	3032976	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	788	,	8844823	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	789	,	3037954	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	790	,	2876255	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	791	,	881163	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	792	,	6442346	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	793	,	3724422	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	794	,	5198520	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	795	,	4449341	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	796	,	7868755	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	797	,	4500859	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	798	,	3131585	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	799	,	4500370	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	800	,	4416124	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	801	,	3588781	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	802	,	4508798	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	803	,	3798595	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	804	,	3134165	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	805	,	4490387	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	806	,	7911395	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	807	,	956656	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	808	,	990687	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	809	,	967122	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	810	,	4500116	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	811	,	5293619	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	812	,	3762348	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	813	,	7933770	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	814	,	6452564	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	815	,	901866	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	816	,	835306	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	817	,	6550838	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	818	,	3758081	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	819	,	3154043	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	820	,	5251243	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	821	,	5889262	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	822	,	4419426	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	823	,	985950	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	824	,	988461	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	825	,	3786898	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	826	,	2892858	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	827	,	3566121	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	828	,	3560716	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	829	,	7974413	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	830	,	6498585	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	831	,	5244824	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	832	,	8789979	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	833	,	5156797	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	834	,	6515897	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	835	,	5186167	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	836	,	3728178	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	837	,	851055	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	838	,	4419431	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	839	,	8778081	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	840	,	3299411	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	841	,	3745138	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	842	,	3618425	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	843	,	835463	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	844	,	3027205	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	845	,	3155872	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	846	,	3797390	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	847	,	3123039	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	848	,	6479415	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	849	,	5234459	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	850	,	3581590	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	851	,	3598482	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	852	,	4428308	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	853	,	3621238	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	854	,	3018961	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	855	,	922813	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	856	,	4403745	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	857	,	6436898	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	858	,	905439	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	859	,	3126307	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	860	,	3028394	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	861	,	3601860	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	862	,	876455	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	863	,	4394864	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	864	,	4429736	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	865	,	3032991	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	866	,	6410334	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	867	,	4446343	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	868	,	3587127	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	869	,	5250819	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	870	,	3125794	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	871	,	5316706	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	872	,	3590429	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	873	,	3155956	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	874	,	796223	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	875	,	3129520	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	876	,	881307	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	877	,	2873295	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	878	,	2872085	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	879	,	986679	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	880	,	3572697	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	881	,	6414204	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	882	,	881179	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	883	,	3582283	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	884	,	5218161	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	885	,	3154232	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	886	,	3798879	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	887	,	5187197	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	888	,	2915861	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	889	,	6421046	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	890	,	875903	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	891	,	4438046	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	892	,	876318	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	893	,	8008095	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	894	,	4485677	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	895	,	6488210	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	896	,	5915260	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	897	,	5240766	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	898	,	10689198	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	899	,	882050	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	900	,	998347	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	901	,	835629	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	902	,	4449338	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	903	,	882061	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	904	,	3573487	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	905	,	3735507	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	906	,	6413099	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	907	,	4449268	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	908	,	4528939	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	909	,	993960	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	910	,	3131801	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	911	,	3619253	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	912	,	6449716	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	913	,	6443053	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	914	,	3759871	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	915	,	3736941	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	916	,	3038079	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	917	,	3767216	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	918	,	3125703	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	919	,	4429658	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	920	,	6432511	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	921	,	6411069	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	922	,	4459991	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	923	,	6514843	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	924	,	6419462	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	925	,	4446320	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	926	,	3125714	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	927	,	6477144	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	928	,	6473216	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	929	,	7911395	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	930	,	3747667	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	931	,	7870797	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	932	,	3599517	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	933	,	7994500	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	934	,	8726639	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	935	,	4446352	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	936	,	3152279	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	937	,	3814045	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	938	,	5190980	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	939	,	3124328	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	940	,	3763274	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	941	,	956654	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	942	,	4494421	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	943	,	4502907	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	944	,	2875670	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	945	,	4490383	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	946	,	6514563	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	947	,	5289256	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	948	,	6410197	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	949	,	6443591	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	950	,	2906518	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	951	,	4499156	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	952	,	8665313	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	953	,	3037840	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	954	,	6513161	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	955	,	7959972	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	956	,	3622438	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	957	,	3132530	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	958	,	4444526	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	959	,	875909	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	960	,	6496751	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	961	,	7905421	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	962	,	3145321	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	963	,	7908992	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	964	,	7932271	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	965	,	5930284	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	966	,	4449288	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	967	,	6418497	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	968	,	3562602	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	969	,	5301276	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	970	,	984809	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	971	,	8803404	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	972	,	7994224	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	973	,	5199236	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	974	,	5286861	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	975	,	784336	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	976	,	3734637	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	977	,	5242711	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	978	,	5242701	,0,1,1,2);
insert into entidad (identidad, noidentificacion, version, idcompania, idtipodocumento, idexttipodocumento) values (	979	,	959112	,0,1,1,2);


/** Insertando persona **/

insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	710	,	'MARTIN',	'TORRICO',	'FERRUFINO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	711	,	'LIDIA NANCY',	'ALVARADO',	'GONZALES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	712	,	'LUCIO',	'PEREZ',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	713	,	'SEBASTIANA',	'RIOS',	'DE PEREZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	714	,	'GABINO',	'SANABRIA',	'LOBO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	715	,	'JESUS OSCAR',	'LEDEZMA',	'ALCOCER',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	716	,	'ELSA',	'PEREZ',	'DE CAMACHO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	717	,	'NEMECIO',	'VELASQUEZ',	'DELGADILLO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	718	,	'FACUNDO',	'ALVARADO',	'CABRERA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	719	,	'JUAN CARLOS',	'MERCADO',	'ESPINOZA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	720	,	'ERNESTO',	'CLAROS',	'GUTIERREZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	721	,	'FIDEL',	'TORRICO',	'FERRUFINO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	722	,	'MARIA',	'QUIROZ',	'DE VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	723	,	'LEIDY',	'LUJAN',	'VALLEJOS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	724	,	'TEODORA',	'SOTO',	'VARGAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	725	,	'FABIANA',	'BARRIENTOS',	'DE ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	726	,	'NICOLAS',	'QUISPE',	'VIDAL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	727	,	'ANACLETA',	'CORDOVA',	'JORDAN DE FIEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	728	,	'CARLA',	'ROSAS',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	729	,	'EMIGDIO',	'GARCIA',	'ARROYO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	730	,	'ANGELA',	'VASQUEZ',	'DE GONZALES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	731	,	'LIBORIO',	'SILVESTRE',	'FERNANDEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	732	,	'JOVITA',	'HERRERA',	'GOSOY',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	733	,	'RUBEN',	'GARCIA',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	734	,	'BETTY CARINA',	'LAIME',	'ANGULO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	735	,	'LUCIANO',	'PONCE',	'FLORES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	736	,	'NORMA',	'QUIROGA',	'COCA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	737	,	'JULIAN',	'VASQUEZ',	'FERREL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	738	,	'JULIAN',	'VASQUEZ',	'FERREL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	739	,	'BEATRIZ',	'CASILLA',	'VDA. DE VEIZAGA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	740	,	'OLIMPIA',	'FLORES',	'ZURITA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	741	,	'DEYSI',	'MURIEL',	'DURAN',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	742	,	'FLORINDA',	'VEIZAGA',	'CASILLA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	743	,	'MATILDE',	'LEON',	'PEREZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	744	,	'SANDRA',	'TENORIO',	'DE ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	745	,	'MARIA',	'SORIA',	'ARRIAS DE MENECES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	746	,	'RECILIA',	'VARGAS',	'DE AVILA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	747	,	'ELISA',	'VARGAS',	'SILES DE ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	748	,	'GREGORIO',	'ROCHA',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	749	,	'CECILIO',	'HINOJOSA',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	750	,	'EZEQUIEL',	'ROJAS',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	751	,	'JACINTO',	'MURIEL',	'CLAROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	752	,	'HUMBERTO',	'VELASCO',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	753	,	'JUAN CARLOS',	'TORRICO',	'ARIAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	754	,	'ALEJANDRO',	'ORELLANA',	'QUINTEROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	755	,	'FLORENCIO',	'MERIDA',	'SILVESTRE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	756	,	'MAXIMA',	'SANCHEZ',	'CAMACHO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	757	,	'SIMON',	'ZURITA',	'MERCADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	758	,	'JOSE LUIS',	'MERCADO',	'HIDALGO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	759	,	'MILDRE',	'VEIZAGA',	'FLORES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	760	,	'ROLANDO',	'GONZALES',	'CALVIMONTES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	761	,	'DAVID JONATAN',	'LEDEZMA',	'ARZE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	762	,	'WILSON',	'MERCADO',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	763	,	'TEODORA ',	'VALLEJOS',	'DURAN',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	764	,	'JUAN CARLOS',	'VARGAS',	'MERIDA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	765	,	'SERGIO',	'CAMACHO',	'MASIAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	766	,	'BENEDICTO',	'RODRIGUEZ',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	767	,	'NELIDA',	'GALINDO',	'DE ZERNA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	768	,	'LUISA',	'ORELLANA',	'MACHUCA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	769	,	'TEODOLINDA',	'MERCADO',	'ZURITA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	770	,	'MARTHA',	'CRESPO',	'DE ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	771	,	'MERY ELIZABETH',	'DELGADO',	'SANCHEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	772	,	'EDUARDA',	'MOLINA',	'M',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	773	,	'MARISABEL',	'ORELLANA',	'MURIEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	774	,	'BERNARDINA',	'ARZE',	'ROCHA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	775	,	'JESUS',	'ROJAS',	'ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	776	,	'MIRIAN',	'VARGAS',	'SUAREZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	777	,	'ABEL',	'VEIZAGA',	'TERCEROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	778	,	'VICTOR',	'MONTAÑO',	'CLAROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	779	,	'WENDY VERONIA',	'LOPEZ',	'PANOZO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	780	,	'CARMEN ROSA',	'VEIZAGA',	'SOTO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	781	,	'INES KARINA',	'LINARES',	'BALDERRAMA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	782	,	'PLACIDO',	'CASTELLON',	'ZANABRIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	783	,	'ELIODORO',	'LIMA',	'SOLIZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	784	,	'ADRIAN',	'SUYO',	'ZURITA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	785	,	'ELIO ALEXANDER',	'ESCOBAR',	'BARRIENTOS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	786	,	'ALBERTO',	'QUIROZ',	'MURIEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	787	,	'ESTEBAN',	'GARCIA',	'ARROYO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	788	,	'NATIVIDAD',	'MOLINA',	'BECERRA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	789	,	'MARITZA',	'RIVERA',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	790	,	'MARINA',	'LAIME',	'DE PONCE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	791	,	'NICOLASA',	'ROJAS',	'GALINDO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	792	,	'INES',	'GONZALES',	'VASQUEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	793	,	'VICTOR',	'MERCADO',	'ALVARADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	794	,	'AURORA',	'PARRA',	'MERCADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	795	,	'FELICIDAD',	'COCA',	'ACERO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	796	,	'ENRIQUETA',	'ARISPE',	'MERCADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	797	,	'ADOLFO',	'PARDO',	'CLAROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	798	,	'JOSE HERNAN',	'VILLAZON',	'MACHADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	799	,	'NOEMI ROXANA',	'SILES',	'DE CALUCHO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	800	,	'NORMA',	'VEIZAGA',	'ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	801	,	'EPIFANIA',	'ESCOBAR',	'DE PARDO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	802	,	'ANA MARIA',	'FERNANDEZ',	'VARGAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	803	,	'SANDRO GREGORIO',	'CALUCHO',	'NAVIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	804	,	'VICTOR',	'ROJAS',	'QUINTEROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	805	,	'VALENTINA',	'ORELLANA',	'DE MOLINA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	806	,	'HILDA',	'ORELLANA',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	807	,	'RENATA',	'QUIROZ',	'JALDIN',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	808	,	'JUANITO',	'SILES',	'VARGAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	809	,	'INES',	'MORALES',	'DE SOLIZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	810	,	'SABINA',	'VEIZAGA',	'DE FERRUFINO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	811	,	'MIRIAM',	'MARZANA',	'CARTAGENA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	812	,	'ELY MIGUELINA',	'FIEL',	'TERCEROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	813	,	'MIRTHA',	'SOLIZ',	'MORALES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	814	,	'MARIA CARMEN',	'PONCE',	'RODRIGUEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	815	,	'ALBINA',	'TORRICO',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	816	,	'RAUL',	'FIGUEROA',	'MERCADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	817	,	'AIDA',	'ANDIA',	'ARISPE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	818	,	'LIZ IVONE',	'GARCIA',	'MENDOZA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	819	,	'RUTH NANCY',	'GARCIA',	'MENDOZA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	820	,	'RICHARDT',	'VELASQUEZ',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	821	,	'ELVIS DEMETRIO',	'BARRERA',	'GUEVARA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	822	,	'TANIA MARLENE',	'ORTUÑO',	'ROCHA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	823	,	'FREDY NELSON',	'ARNEZ',	'VARGAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	824	,	'ENRIQUE',	'MELGAREJO',	'CHOQUE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	825	,	'PETRONILA',	'ROJAS',	'DE GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	826	,	'SEGUNDINA',	'GARCIA',	'MENDEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	827	,	'SILVIA',	'FIGUEROA',	'DE GARNICA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	828	,	'NICOLASA',	'SALDAÑA',	'ONOFRE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	829	,	'SANTA BENITA',	'QUISPE',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	830	,	'MARISABEL',	'SARABIA',	'SOLIZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	831	,	'CRESENCIO',	'DELGADILLO',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	832	,	'JULIA',	'MAMANI',	'CHURA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	833	,	'GELDA',	'TENORIO',	'VASQUEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	834	,	'MONICA',	'VASQUEZ',	'DE TENORIO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	835	,	'MARINA',	'UGARTE',	'CHAVEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	836	,	'JOSE OSVALDO',	'FERNANDEZ',	'VEIZAGA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	837	,	'FREDDY',	'AGUILAR',	'CHAMBI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	838	,	'FERNANDO',	'AGUILAR',	'CRUZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	839	,	'NANCY',	'ORELLANA',	'SALAZAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	840	,	'PAULINA',	'CRUZ',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	841	,	'HORTENCIA',	'ZERNA',	'MALDONADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	842	,	'MARINA',	'MALDONADO',	'DE CASTELLON',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	843	,	'FELIX FREDDY',	'TORRICO',	'MONTERO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	844	,	'YOLA',	'URIONA',	'DE GUEVARA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	845	,	'PABLO',	'MIRANDA',	'CONDORI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	846	,	'OLIMPIA',	'VALLEJOS',	'DE CANCHI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	847	,	'EDMUNDO',	'GONZALES',	'VARGAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	848	,	'EDGAR',	'GONZALES',	'CALVIMONTES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	849	,	'DELIA',	'CANCHI',	'VALLEJOS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	850	,	'GREGORIO',	'VEIZAGA',	'CAMACHO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	851	,	'HUGO',	'IRIARTE',	'ESCALERA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	852	,	'ANDRES AMERICO',	'VARIAS',	'ESCALERA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	853	,	'ELIZABETH',	'VELASCO',	'QUINTANILLA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	854	,	'MARGARITA',	'CORDOVA',	'ORTIZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	855	,	'EUFRONIO',	'ARISPE',	'TORRICO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	856	,	'ROXANA',	'VARGAS',	'DE COLQUE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	857	,	'YVAN',	'COLQUE',	'CANO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	858	,	'AURELIO',	'VILLARROEL',	'CESPEDES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	859	,	'SABINA',	'PARRA',	'DE VIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	860	,	'JESUS MIGUEL',	'CRESPO',	'CLAROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	861	,	'ROMAN',	'PIZO',	'BELTRAN',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	862	,	'ANTONIO',	'LOPEZ',	'PONCE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	863	,	'MARGARITA',	'VILLARROEL',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	864	,	'SERGIO',	'SALAZAR',	'BUSTAMANTE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	865	,	'CELESTINO',	'VILLARROEL',	'VIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	866	,	'NEMECIA',	'BUSTAMANTE',	'DE MOLINA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	867	,	'DIONICIO',	'ROJAS',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	868	,	'FELICIDAD',	'VILLARROEL',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	869	,	'BERTHA',	'GARCIA',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	870	,	'SANTUSA',	'HINOJOSA',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	871	,	'ABEL',	'QUINTEROS',	'HIDALGO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	872	,	'HENRY',	'OVANDO',	'VASQUEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	873	,	'CASILDA',	'ORELLANA',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	874	,	'MACARIO',	'GONZALES',	'TORRICO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	875	,	'RAMON',	'ALVAREZ',	'CHAMBI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	876	,	'MAXIMILIANA',	'VIDAL',	'DE CAVERO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	877	,	'MARCELINA',	'MEJIA',	'DE ALVAREZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	878	,	'ROBERTO',	'CAVERO',	'RICALDEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	879	,	'YOLANDA',	'CAVERO',	'RICALDEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	880	,	'ELSA',	'ARNEZ',	'TAPIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	881	,	'MARIA JIMENA',	'ALVAREZ',	'MEJIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	882	,	'ANDRES',	'VILLARROEL',	'MAMANI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	883	,	'EUGENIA',	'ZENTENO',	'SORIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	884	,	'PAULINA',	'VILLARROEL',	'ZENTENO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	885	,	'MIGUEL',	'GONZALES',	'G',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	886	,	'TOMASA',	'ZENTENO',	'ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	887	,	'PONCIANO',	'QUISPE',	'HIGUERA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	888	,	'MODESTO',	'ZARATE',	'SAAVEDRA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	889	,	'BALVINA',	'VEIZAGA',	'LUIZAGA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	890	,	'ENRIQUE',	'PARRA',	'MERIDA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	891	,	'NANCY',	'VILLARROEL',	'DURAN',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	892	,	'NICOLASA',	'GARCIA',	'DE SALAZAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	893	,	'NORA',	'RIOS',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	894	,	'FIDEL',	'CHOQUE',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	895	,	'SINFOROSA',	'GARCIA',	'MEJIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	896	,	'MARLENE',	'PARRA',	'MERCADO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	897	,	'LOYDA',	'HERRERA',	'GODOY',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	898	,	'HUMBERTO',	'MERCADO',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	899	,	'PAULINO',	'SENZANO',	'MAMANI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	900	,	'JULIA',	'ROSAS',	'ZENSANO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	901	,	'PACIFICO',	'ROSAS',	'SENZANO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	902	,	'EVARISTO',	'MARIN',	'SILES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	903	,	'JOSE',	'CADIMA',	'MERINO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	904	,	'AIDEE',	'ROJAS',	'ROSAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	905	,	'DANIEL',	'SILES',	'COLQUE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	906	,	'PONCIANA',	'HERRERA',	'DE MOLINA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	907	,	'LIDIA',	'GONZALES',	'VELIZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	908	,	'SABINA',	'ROJAS',	'DE ROSAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	909	,	'ELVIRA',	'CONDORI',	'DE ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	910	,	'JORGE',	'PARDO',	'CLAROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	911	,	'TERESA',	'PARDO',	'DE VILLAZON',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	912	,	'MARCIA',	'JALDIN',	'HERBAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	913	,	'DELIA',	'CLAROS',	'MORALES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	914	,	'ANGEL',	'HINOJOSA',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	915	,	'FRUCTUOSO',	'GARCIA',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	916	,	'MARGARITA',	'GARCIA',	'DE ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	917	,	'FRUCTUOSA',	'MURIEL',	'RIOS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	918	,	'JULIAN',	'ROJAS',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	919	,	'ALBINA',	'VALLEJOS',	'DE GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	920	,	'MARTHA',	'GARCIA',	'VALLEJOS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	921	,	'JOSE ANTONIO',	'OCHOA',	'CAMACHO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	922	,	'MARITZA',	'VALLEJOS',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	923	,	'EPIFANIO',	'RIOS',	'LLANOS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	924	,	'SEVERINA',	'ORELLANA',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	925	,	'ROBERTO',	'ROJAS',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	926	,	'CONSTANCIA',	'COSSIO',	'SILVESTRE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	927	,	'ALEJANDRINA',	'ORELLANA',	'DE TERRAZAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	928	,	'PASTOR',	'ROJAS',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	929	,	'HILDA',	'ORELLANA',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	930	,	'FILOMENA',	'GARCIA',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	931	,	'MARTHA',	'ORELLANA',	'GARCIA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	932	,	'BASILIO',	'ORELLANA',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	933	,	'CELESTINA',	'MERIDA',	'SILVESTRE',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	934	,	'VILMA',	'PIZO',	'TERRAZAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	935	,	'CARLOS',	'ROJAS',	'QUINTEROS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	936	,	'CIRILA',	'ARISPE',	'DE UREÑA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	937	,	'FLORENCIA',	'ESCOBAR',	'PINTO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	938	,	'YOVANA',	'RODRIGUEZ',	'QUIROZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	939	,	'ROSALIA',	'FLORES',	'ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	940	,	'ANTONIETA',	'ESCOBAR',	'E',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	941	,	'LIBORIA',	'PINTO',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	942	,	'AURELIO',	'ROSAS',	'FERNANDEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	943	,	'NANCY',	'VILLARROEL',	'DE SALAZAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	944	,	'MARIA',	'QUIROZ',	'DE VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	945	,	'LEONARDO',	'ORELLANA',	'MACHUCA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	946	,	'DANEYVA JEMINA',	'UNZUETA',	'RIVERA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	947	,	'BELINDA',	'CABRERA',	'CABRERA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	948	,	'INES',	'GARCIA',	'VILLARROEL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	949	,	'MARIA ELENA',	'GUZMAN',	'PEREIRA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	950	,	'CLIZERIO TEODOLINDO',	'GUEVARA',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	951	,	'FELIPA',	'GODOY',	'ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	952	,	'PILAR',	'PONCE',	'COCA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	953	,	'PEDRO',	'GONZALES',	'LIZARAZU',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	954	,	'PRIMITIVA',	'CADIMA',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	955	,	'JUANA',	'CADIMA',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	956	,	'SILVERIA',	'CARDOZO',	'CONDORI',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	957	,	'EMETERIA',	'GONZALES',	'DE GUAMAN',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	958	,	'ZACARIAS',	'OROPEZA',	'GONZALES',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	959	,	'DIONICIA',	'MERCADO',	'DE ZURITA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	960	,	'MODESTA',	'RODRIGUEZ',	'DE PARDO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	961	,	'NILZA JIMENA',	'ARISPE',	'ESCOBAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	962	,	'ADELAIDA',	'ROJAS',	'DE SEJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	963	,	'GARY',	'PONCE',	'LAIME',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	964	,	'JHENNY DOLY',	'CAVERO',	'VIDAL',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	965	,	'MATILDA',	'MUNACHI',	'SANTA ANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	966	,	'ROBERTA',	'GODOY',	'ENCINAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	967	,	'VICENTE',	'MOLINA',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	968	,	'SIMONA',	'MALDONADO',	'PEREIRA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	969	,	'MARIA',	'SAGARDIA',	'PINTO',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	970	,	'MARGARITA',	'FLORES',	'REA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	971	,	'CIRIACO',	'SALAZAR',	'ROJAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	972	,	'SENOBIA',	'LABRA',	'VEIZAGA DE SALAZAR',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	973	,	'TITO',	'ARNEZ',	'ZEGARRA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	974	,	'PALMIRA DEYSI',	'CANELAS',	'TERRAZAS',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	975	,	'LIBORIA',	'ESCOBAR',	'DE VELASQUEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	976	,	'TEODORO',	'ESPINOZA',	'RODRIGUEZ',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	977	,	'GREBY',	'FLORES',	'ORELLANA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	978	,	'LIDIA',	'ORELLANA',	'ESPINOZA',	1);
insert into persona (idpersona, nombres, apellidopaterno, apellidomaterno, idcompania) values (	979	,	'PONCIANA',	'VARGAS',	'TORRICO',	1);

/** Asociando Socio con Persona **/

update socio set idpersona = 	710	 where idsocio = 	231	;
update socio set idpersona = 	711	 where idsocio = 	232	;
update socio set idpersona = 	712	 where idsocio = 	233	;
update socio set idpersona = 	713	 where idsocio = 	234	;
update socio set idpersona = 	714	 where idsocio = 	235	;
update socio set idpersona = 	715	 where idsocio = 	236	;
update socio set idpersona = 	716	 where idsocio = 	237	;
update socio set idpersona = 	717	 where idsocio = 	239	;
update socio set idpersona = 	718	 where idsocio = 	240	;
update socio set idpersona = 	719	 where idsocio = 	242	;
update socio set idpersona = 	720	 where idsocio = 	243	;
update socio set idpersona = 	721	 where idsocio = 	244	;
update socio set idpersona = 	722	 where idsocio = 	246	;
update socio set idpersona = 	723	 where idsocio = 	247	;
update socio set idpersona = 	724	 where idsocio = 	250	;
update socio set idpersona = 	725	 where idsocio = 	251	;
update socio set idpersona = 	726	 where idsocio = 	252	;
update socio set idpersona = 	727	 where idsocio = 	253	;
update socio set idpersona = 	728	 where idsocio = 	254	;
update socio set idpersona = 	729	 where idsocio = 	255	;
update socio set idpersona = 	730	 where idsocio = 	257	;
update socio set idpersona = 	731	 where idsocio = 	258	;
update socio set idpersona = 	732	 where idsocio = 	259	;
update socio set idpersona = 	733	 where idsocio = 	260	;
update socio set idpersona = 	734	 where idsocio = 	261	;
update socio set idpersona = 	735	 where idsocio = 	262	;
update socio set idpersona = 	736	 where idsocio = 	263	;
update socio set idpersona = 	737	 where idsocio = 	264	;
update socio set idpersona = 	738	 where idsocio = 	265	;
update socio set idpersona = 	739	 where idsocio = 	266	;
update socio set idpersona = 	740	 where idsocio = 	267	;
update socio set idpersona = 	741	 where idsocio = 	268	;
update socio set idpersona = 	742	 where idsocio = 	269	;
update socio set idpersona = 	743	 where idsocio = 	271	;
update socio set idpersona = 	744	 where idsocio = 	272	;
update socio set idpersona = 	745	 where idsocio = 	273	;
update socio set idpersona = 	746	 where idsocio = 	274	;
update socio set idpersona = 	747	 where idsocio = 	275	;
update socio set idpersona = 	748	 where idsocio = 	276	;
update socio set idpersona = 	749	 where idsocio = 	277	;
update socio set idpersona = 	750	 where idsocio = 	278	;
update socio set idpersona = 	751	 where idsocio = 	279	;
update socio set idpersona = 	752	 where idsocio = 	280	;
update socio set idpersona = 	753	 where idsocio = 	282	;
update socio set idpersona = 	754	 where idsocio = 	283	;
update socio set idpersona = 	755	 where idsocio = 	284	;
update socio set idpersona = 	756	 where idsocio = 	285	;
update socio set idpersona = 	757	 where idsocio = 	286	;
update socio set idpersona = 	758	 where idsocio = 	287	;
update socio set idpersona = 	759	 where idsocio = 	288	;
update socio set idpersona = 	760	 where idsocio = 	289	;
update socio set idpersona = 	761	 where idsocio = 	291	;
update socio set idpersona = 	762	 where idsocio = 	292	;
update socio set idpersona = 	763	 where idsocio = 	293	;
update socio set idpersona = 	764	 where idsocio = 	294	;
update socio set idpersona = 	765	 where idsocio = 	295	;
update socio set idpersona = 	766	 where idsocio = 	296	;
update socio set idpersona = 	767	 where idsocio = 	297	;
update socio set idpersona = 	768	 where idsocio = 	298	;
update socio set idpersona = 	769	 where idsocio = 	299	;
update socio set idpersona = 	770	 where idsocio = 	300	;
update socio set idpersona = 	771	 where idsocio = 	301	;
update socio set idpersona = 	772	 where idsocio = 	302	;
update socio set idpersona = 	773	 where idsocio = 	303	;
update socio set idpersona = 	774	 where idsocio = 	304	;
update socio set idpersona = 	775	 where idsocio = 	305	;
update socio set idpersona = 	776	 where idsocio = 	306	;
update socio set idpersona = 	777	 where idsocio = 	307	;
update socio set idpersona = 	778	 where idsocio = 	308	;
update socio set idpersona = 	779	 where idsocio = 	309	;
update socio set idpersona = 	780	 where idsocio = 	310	;
update socio set idpersona = 	781	 where idsocio = 	311	;
update socio set idpersona = 	782	 where idsocio = 	583	;
update socio set idpersona = 	783	 where idsocio = 	584	;
update socio set idpersona = 	784	 where idsocio = 	585	;
update socio set idpersona = 	785	 where idsocio = 	586	;
update socio set idpersona = 	786	 where idsocio = 	587	;
update socio set idpersona = 	787	 where idsocio = 	588	;
update socio set idpersona = 	788	 where idsocio = 	589	;
update socio set idpersona = 	789	 where idsocio = 	590	;
update socio set idpersona = 	790	 where idsocio = 	591	;
update socio set idpersona = 	791	 where idsocio = 	592	;
update socio set idpersona = 	792	 where idsocio = 	593	;
update socio set idpersona = 	793	 where idsocio = 	594	;
update socio set idpersona = 	794	 where idsocio = 	595	;
update socio set idpersona = 	795	 where idsocio = 	596	;
update socio set idpersona = 	796	 where idsocio = 	597	;
update socio set idpersona = 	797	 where idsocio = 	598	;
update socio set idpersona = 	798	 where idsocio = 	599	;
update socio set idpersona = 	799	 where idsocio = 	600	;
update socio set idpersona = 	800	 where idsocio = 	601	;
update socio set idpersona = 	801	 where idsocio = 	603	;
update socio set idpersona = 	802	 where idsocio = 	604	;
update socio set idpersona = 	803	 where idsocio = 	605	;
update socio set idpersona = 	804	 where idsocio = 	606	;
update socio set idpersona = 	805	 where idsocio = 	607	;
update socio set idpersona = 	806	 where idsocio = 	608	;
update socio set idpersona = 	807	 where idsocio = 	609	;
update socio set idpersona = 	808	 where idsocio = 	610	;
update socio set idpersona = 	809	 where idsocio = 	611	;
update socio set idpersona = 	810	 where idsocio = 	612	;
update socio set idpersona = 	811	 where idsocio = 	613	;
update socio set idpersona = 	812	 where idsocio = 	614	;
update socio set idpersona = 	813	 where idsocio = 	615	;
update socio set idpersona = 	814	 where idsocio = 	616	;
update socio set idpersona = 	815	 where idsocio = 	617	;
update socio set idpersona = 	816	 where idsocio = 	618	;
update socio set idpersona = 	817	 where idsocio = 	622	;
update socio set idpersona = 	818	 where idsocio = 	623	;
update socio set idpersona = 	819	 where idsocio = 	624	;
update socio set idpersona = 	820	 where idsocio = 	625	;
update socio set idpersona = 	821	 where idsocio = 	626	;
update socio set idpersona = 	822	 where idsocio = 	627	;
update socio set idpersona = 	823	 where idsocio = 	629	;
update socio set idpersona = 	824	 where idsocio = 	630	;
update socio set idpersona = 	825	 where idsocio = 	631	;
update socio set idpersona = 	826	 where idsocio = 	632	;
update socio set idpersona = 	827	 where idsocio = 	633	;
update socio set idpersona = 	828	 where idsocio = 	634	;
update socio set idpersona = 	829	 where idsocio = 	635	;
update socio set idpersona = 	830	 where idsocio = 	636	;
update socio set idpersona = 	831	 where idsocio = 	637	;
update socio set idpersona = 	832	 where idsocio = 	638	;
update socio set idpersona = 	833	 where idsocio = 	639	;
update socio set idpersona = 	834	 where idsocio = 	640	;
update socio set idpersona = 	835	 where idsocio = 	642	;
update socio set idpersona = 	836	 where idsocio = 	643	;
update socio set idpersona = 	837	 where idsocio = 	644	;
update socio set idpersona = 	838	 where idsocio = 	645	;
update socio set idpersona = 	839	 where idsocio = 	653	;
update socio set idpersona = 	840	 where idsocio = 	654	;
update socio set idpersona = 	841	 where idsocio = 	656	;
update socio set idpersona = 	842	 where idsocio = 	660	;
update socio set idpersona = 	843	 where idsocio = 	662	;
update socio set idpersona = 	844	 where idsocio = 	663	;
update socio set idpersona = 	845	 where idsocio = 	664	;
update socio set idpersona = 	846	 where idsocio = 	665	;
update socio set idpersona = 	847	 where idsocio = 	666	;
update socio set idpersona = 	848	 where idsocio = 	667	;
update socio set idpersona = 	849	 where idsocio = 	668	;
update socio set idpersona = 	850	 where idsocio = 	669	;
update socio set idpersona = 	851	 where idsocio = 	670	;
update socio set idpersona = 	852	 where idsocio = 	671	;
update socio set idpersona = 	853	 where idsocio = 	672	;
update socio set idpersona = 	854	 where idsocio = 	673	;
update socio set idpersona = 	855	 where idsocio = 	674	;
update socio set idpersona = 	856	 where idsocio = 	676	;
update socio set idpersona = 	857	 where idsocio = 	677	;
update socio set idpersona = 	858	 where idsocio = 	678	;
update socio set idpersona = 	859	 where idsocio = 	679	;
update socio set idpersona = 	860	 where idsocio = 	680	;
update socio set idpersona = 	861	 where idsocio = 	681	;
update socio set idpersona = 	862	 where idsocio = 	682	;
update socio set idpersona = 	863	 where idsocio = 	683	;
update socio set idpersona = 	864	 where idsocio = 	684	;
update socio set idpersona = 	865	 where idsocio = 	685	;
update socio set idpersona = 	866	 where idsocio = 	686	;
update socio set idpersona = 	867	 where idsocio = 	687	;
update socio set idpersona = 	868	 where idsocio = 	688	;
update socio set idpersona = 	869	 where idsocio = 	689	;
update socio set idpersona = 	870	 where idsocio = 	690	;
update socio set idpersona = 	871	 where idsocio = 	691	;
update socio set idpersona = 	872	 where idsocio = 	693	;
update socio set idpersona = 	873	 where idsocio = 	694	;
update socio set idpersona = 	874	 where idsocio = 	695	;
update socio set idpersona = 	875	 where idsocio = 	696	;
update socio set idpersona = 	876	 where idsocio = 	697	;
update socio set idpersona = 	877	 where idsocio = 	698	;
update socio set idpersona = 	878	 where idsocio = 	699	;
update socio set idpersona = 	879	 where idsocio = 	700	;
update socio set idpersona = 	880	 where idsocio = 	701	;
update socio set idpersona = 	881	 where idsocio = 	702	;
update socio set idpersona = 	882	 where idsocio = 	703	;
update socio set idpersona = 	883	 where idsocio = 	704	;
update socio set idpersona = 	884	 where idsocio = 	705	;
update socio set idpersona = 	885	 where idsocio = 	706	;
update socio set idpersona = 	886	 where idsocio = 	707	;
update socio set idpersona = 	887	 where idsocio = 	708	;
update socio set idpersona = 	888	 where idsocio = 	709	;
update socio set idpersona = 	889	 where idsocio = 	710	;
update socio set idpersona = 	890	 where idsocio = 	711	;
update socio set idpersona = 	891	 where idsocio = 	712	;
update socio set idpersona = 	892	 where idsocio = 	713	;
update socio set idpersona = 	893	 where idsocio = 	714	;
update socio set idpersona = 	894	 where idsocio = 	715	;
update socio set idpersona = 	895	 where idsocio = 	716	;
update socio set idpersona = 	896	 where idsocio = 	717	;
update socio set idpersona = 	897	 where idsocio = 	718	;
update socio set idpersona = 	898	 where idsocio = 	719	;
update socio set idpersona = 	899	 where idsocio = 	720	;
update socio set idpersona = 	900	 where idsocio = 	721	;
update socio set idpersona = 	901	 where idsocio = 	722	;
update socio set idpersona = 	902	 where idsocio = 	723	;
update socio set idpersona = 	903	 where idsocio = 	724	;
update socio set idpersona = 	904	 where idsocio = 	725	;
update socio set idpersona = 	905	 where idsocio = 	726	;
update socio set idpersona = 	906	 where idsocio = 	727	;
update socio set idpersona = 	907	 where idsocio = 	728	;
update socio set idpersona = 	908	 where idsocio = 	729	;
update socio set idpersona = 	909	 where idsocio = 	730	;
update socio set idpersona = 	910	 where idsocio = 	731	;
update socio set idpersona = 	911	 where idsocio = 	732	;
update socio set idpersona = 	912	 where idsocio = 	733	;
update socio set idpersona = 	913	 where idsocio = 	734	;
update socio set idpersona = 	914	 where idsocio = 	735	;
update socio set idpersona = 	915	 where idsocio = 	736	;
update socio set idpersona = 	916	 where idsocio = 	737	;
update socio set idpersona = 	917	 where idsocio = 	738	;
update socio set idpersona = 	918	 where idsocio = 	739	;
update socio set idpersona = 	919	 where idsocio = 	740	;
update socio set idpersona = 	920	 where idsocio = 	741	;
update socio set idpersona = 	921	 where idsocio = 	742	;
update socio set idpersona = 	922	 where idsocio = 	743	;
update socio set idpersona = 	923	 where idsocio = 	744	;
update socio set idpersona = 	924	 where idsocio = 	745	;
update socio set idpersona = 	925	 where idsocio = 	746	;
update socio set idpersona = 	926	 where idsocio = 	747	;
update socio set idpersona = 	927	 where idsocio = 	748	;
update socio set idpersona = 	928	 where idsocio = 	749	;
update socio set idpersona = 	929	 where idsocio = 	750	;
update socio set idpersona = 	930	 where idsocio = 	751	;
update socio set idpersona = 	931	 where idsocio = 	752	;
update socio set idpersona = 	932	 where idsocio = 	753	;
update socio set idpersona = 	933	 where idsocio = 	754	;
update socio set idpersona = 	934	 where idsocio = 	755	;
update socio set idpersona = 	935	 where idsocio = 	756	;
update socio set idpersona = 	936	 where idsocio = 	757	;
update socio set idpersona = 	937	 where idsocio = 	758	;
update socio set idpersona = 	938	 where idsocio = 	759	;
update socio set idpersona = 	939	 where idsocio = 	760	;
update socio set idpersona = 	940	 where idsocio = 	761	;
update socio set idpersona = 	941	 where idsocio = 	763	;
update socio set idpersona = 	942	 where idsocio = 	764	;
update socio set idpersona = 	943	 where idsocio = 	765	;
update socio set idpersona = 	944	 where idsocio = 	766	;
update socio set idpersona = 	945	 where idsocio = 	767	;
update socio set idpersona = 	946	 where idsocio = 	768	;
update socio set idpersona = 	947	 where idsocio = 	771	;
update socio set idpersona = 	948	 where idsocio = 	774	;
update socio set idpersona = 	949	 where idsocio = 	775	;
update socio set idpersona = 	950	 where idsocio = 	776	;
update socio set idpersona = 	951	 where idsocio = 	777	;
update socio set idpersona = 	952	 where idsocio = 	778	;
update socio set idpersona = 	953	 where idsocio = 	779	;
update socio set idpersona = 	954	 where idsocio = 	780	;
update socio set idpersona = 	955	 where idsocio = 	781	;
update socio set idpersona = 	956	 where idsocio = 	782	;
update socio set idpersona = 	957	 where idsocio = 	783	;
update socio set idpersona = 	958	 where idsocio = 	784	;
update socio set idpersona = 	959	 where idsocio = 	785	;
update socio set idpersona = 	960	 where idsocio = 	786	;
update socio set idpersona = 	961	 where idsocio = 	787	;
update socio set idpersona = 	962	 where idsocio = 	788	;
update socio set idpersona = 	963	 where idsocio = 	790	;
update socio set idpersona = 	964	 where idsocio = 	791	;
update socio set idpersona = 	965	 where idsocio = 	793	;
update socio set idpersona = 	966	 where idsocio = 	794	;
update socio set idpersona = 	967	 where idsocio = 	795	;
update socio set idpersona = 	968	 where idsocio = 	796	;
update socio set idpersona = 	969	 where idsocio = 	797	;
update socio set idpersona = 	970	 where idsocio = 	798	;
update socio set idpersona = 	971	 where idsocio = 	799	;
update socio set idpersona = 	972	 where idsocio = 	800	;
update socio set idpersona = 	973	 where idsocio = 	801	;
update socio set idpersona = 	974	 where idsocio = 	804	;
update socio set idpersona = 	975	 where idsocio = 	807	;
update socio set idpersona = 	976	 where idsocio = 	813	;
update socio set idpersona = 	977	 where idsocio = 	814	;
update socio set idpersona = 	978	 where idsocio = 	815	;
update socio set idpersona = 	979	 where idsocio = 	816	;





