/** 06.08.2019 **/

-- Para F.Cisc
delete from arcgms where cuenta in (4110000000, 4110100000, 4110110000);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110000000','CARGOS POR OBLIGACIONES CON EL PUBLICO','4100000000',null,null,'3',null,null,'9','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110200000','Int.Obligaciones por Cuentas de Ahorros','4100000000',null,null,'4',null,null,'9','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110210000','Int.Obligaciones Ahorros M.N.','4100000000',null,null,'5',null,null,'9','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110210100','Int.Obligaciones Cajas de Ahorros M.N.','4100000000',null,null,'6',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110210200','Int.Obligaciones Ahorros Socios M.N.','4100000000',null,null,'6',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110220000','Int.Obligaciones Ahorros M.E.','4100000000',null,null,'5',null,null,'9','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110220100','Int.Obligaciones Cajas de Ahorros ME','4100000000',null,null,'6',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110220200','Int.s/Ahorros Voluntarios ME','4100000000',null,null,'6',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110230000','Int.Obligaciones por Ctas.Ahorros MV','4100000000',null,null,'5',null,null,'9','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110230100','Int.s/Ahorros Voluntarios MV','4100000000',null,null,'6',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110230200','Int.Obligaciones por Ctas.Ahorros MV','4100000000',null,null,'6',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110300000','Intereses por Depositos a Plazo Fijo','4100000000',null,null,'4',null,null,'9','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110310000','Intereses por Depositos a Plazo Fijo MN','4100000000',null,null,'5',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);
insert into arcgms (`cuenta`, `descri`, `cta_raiz`, `cta_niv3`, `cn_ana`, `cn_nivel`, `cn_dv`, `cn_tip`, `cn_act`, `no_cia`, `clase`, `tipo`, `activa`, `permite_iva`, `ind_presup`, `creditos`, `moneda`, `debitos`, `saldo_mes_ant_dol`, `saldo_per_ant_dol`, `creditos_dol`, `debitos_dol`, `gru_cta`, `permiso_con`, `exije_cc`, `permiso_afijo`, `permiso_cxp`, `permiso_cxc`, `permiso_che`, `permiso_inv`, `f_inactiva`, `ind_mov`, `saldo_mes_ant`, `saldo_per_ant`) values('4110320000','Intereses por Depositos a Plazo Fijo ME','4100000000',null,null,'5',null,null,'0','01',null,'E','S',null,null,null,'P',null,null,null,null,null,null,null,null,null,null,null,null,null,null,'S',null,null);

-- 
select *
from `arcgms` d
where d.`cuenta` in (
4110000000,
4110200000,
4110210000,
4110210100,
4110210200,
4110220000,
4110220100,
4110220200,
4110230000,
4110230100,
4110230200,
4110300000,
4110310000,
4110320000
);
